In [1]:
#my first python program
Name = input("Enter ypur name")
print("Hello ",Name)


Enter ypur nameRana
Hello  Rana


# This is a title.
## This is a Heading.
### This is a subheading.
#### This is as small as a heading can get.
##### The fifth hash makes it italic.


` rana `

In [3]:
str = "  sdfs"
print(str.lstrip())

sdfs


In [24]:
a = ['a','b','c','d','e']

In [27]:
#a.insert(4,5)
a.append('f')
print(a)
#a.remove(5)
a.pop()
print(a)

['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e']


In [3]:
input_tuple = ('Monty Python', 'British', 1969)

list_demo = list(input_tuple)# Write your code here
list_demo.extend(['Monty Python', 'British', 1969])
print(list_demo)
tuple_2 = tuple(list_demo)
# Make sure to name the final tuple 'tuple_2'
print(tuple_2)

['Monty Python', 'British', 1969, 'Monty Python', 'British', 1969]
('Monty Python', 'British', 1969, 'Monty Python', 'British', 1969)


In [8]:
input_dict={'Name': 'Monty', 'Profession': 'Singer' }
print(input_dict.get('ab'))

None


In [12]:
d = {'a':1, 'b':2}
print(d)

{'a': 1, 'b': 2}


In [18]:
dict_1 = {'Python':40, 'R':45}
del dict_1('R':40)
print(dict_1)

SyntaxError: invalid syntax (<ipython-input-18-a9aca475ded3>, line 2)

In [22]:
input_list = [[1,2,3,4,5,6],[2,3,4,5,6,7,8,9]]
list_1 = input_list[0]
list_2 = input_list[1]

set_1 = set(list_1)
set_2 = set(list_2)
answer_1 = set(set_1.difference(set_2))
answer_2 = set(set_1.symmetric_difference(set_2))

print(answer_1)
print(answer_2)

{1}
{8, 1, 9, 7}


In [34]:
import ast,sys
input_str = 'lpha'
vowel_list = ['a','e','i','o','u']
if input_str[0].lower() in vowel_list :
    print("YES")
else :
    print("NO")

NO


In [53]:
char = ''
n = 8
if(n%2 != 0):
    print("Please enter an even no : ")
else:
   for i in range(1,n):
    if(i<=n/2):
        char += '*'
        print(char)
    else:
        char = char[:-1]
        print(char)
        


*
**
***
****
***
**
*


In [56]:
for i in range(1,6):
    if (i % 3 == 0):
        print(str(i) + " is Divisible by 3")
        pass

    print(str(i) + " is not divisible by 3")

1 is not divisible by 3
2 is not divisible by 3
3 is Divisible by 3
3 is not divisible by 3
4 is not divisible by 3
5 is not divisible by 3


In [59]:
n = 4
sq_list = [x**2 for x in range(1,n+1)]
print(sq_list)

[1, 4, 9, 16]


In [63]:
input_list=['wood', 'old', 'apple', 'big', 'item', 'euphoria']
vowels_list=['a','e','i','o','u']
list_start_with_vowel = [word for word in input_list if word[0].lower() in vowels_list]
print(list_start_with_vowel)

['old', 'apple', 'item', 'euphoria']


In [67]:
product_list = []
for i in range(10):
    for j in range(10,20):
        product_list.append(i*j)
print(product_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171]


In [70]:
single_word_list=[]
paragraph = ["There was a fox." , 'It was brown in color.', "It was seen near that farm sometime back"]

single_word_list = [word for sentence in paragraph for word in sentence.split(" ")]
print(single_word_list)



['There', 'was', 'a', 'fox.', 'It', 'was', 'brown', 'in', 'color.', 'It', 'was', 'seen', 'near', 'that', 'farm', 'sometime', 'back']


In [72]:
n = 6

dictionary = {i:j for i in range(1,n+1) j = i**2}
print(dictionary)

SyntaxError: invalid syntax (<ipython-input-72-e940d081175b>, line 3)

In [73]:
a = 2
b = 3

greater = lambda x,y : x if x>y else y

print(greater(a,b))

3


In [78]:
def say(message, times = 2):
    print(message * times)

say('Hello')
say('World')

print(sum[true,true])

HelloHello
WorldWorld


NameError: name 'true' is not defined

In [80]:
input_list =  ['hdjk', 'salsap', 'sherpa']
strart_with_s = lambda x : x[0].lower() == 's' and x[-1].lower() == 'p'
print(list(filter(strart_with_s,input_list)))

['salsap']


In [82]:
input_list = [5,3,9,77,45,89]
from functools import reduce

answer = reduce(lambda x,y : if x>y else y, input_list)

print(answer)

SyntaxError: invalid syntax (<ipython-input-82-603e89aeb1b9>, line 4)

In [89]:
S = "I love Python"
print(S[0:-1])

I love Pytho


In [91]:
L = [1, 2, 3]
print(L*2)

[1, 2, 3, 1, 2, 3]


In [93]:
def my_func(*args):
    return(sum(args))

print(my_func(1,2,3,4,5))
print(my_func(6,7,8))

15
21


In [96]:
import numpy as np
narray = np.full((3,4),1)
print(narray)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [117]:
block = np.zeros([5,5],dtype=int)
block[1::2,0::2] = 1
block[0::2,1::2] = 1
print(block)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [118]:
a = [1,2,3,4,5,6,7,8,9,10]
print("A : " , a)
print(":: : " ,a[0::2])


A :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
:: :  [1, 3, 5, 7, 9]


In [1]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,0]

import numpy as np
array_1 = np.array([list_1,list_2])#,list_2]#Type your answer here
print(array_1)
print(array_1.shape)
print(array_1.ndim)


[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
2


In [2]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))

None
None
None
