In [2]:
import numpy as np
import pandas as pd

In [10]:
#Linear Combination

v1 = np.array([2,3])
v2 = np.array([8,9])
m = 5
n = 6
#Linear combination vector would be m*v1+n*v2
# that is (m*2+n*8),(m*3+n*9)

lincom  = m*v1 + n*v2
print(lincom)

[58 69]


In [12]:
# Reverse way we can find m & n of a Linear combination of two vectors v1 & v2
lincom2 = ([58,69])
vec_set = np.array([[2,3],[8,9]])
m,n = np.linalg.solve(vec_set,lincom2)
m,n

(-52.5, 54.333333333333336)

In [14]:
lincom3  = ([19,29,54])
setvec2 = np.array([[1,2,3],[4,5,6],[1,2,6]])
m,n = np.linalg.solve(setvec2, lincom3)
m,n

ValueError: too many values to unpack (expected 2)

In [17]:
#Linear transformation
a = [[1,2],[-2,3],[-2,1],[3,7],[4,5],[6,4]]
b = ['X','Y']
c = pd.DataFrame(a,columns=b)
c

X  Y
0  1  2
1 -2  3
2 -2  1
3  3  7
4  4  5
5  6  4

In [19]:
## Now let's denote the linear transformation matrix.
## (2,0) and (0,1) are the vectors that would denote the columns of this matrix.
## Therefore (2,0) and (0,1) would be the rows
L = np.array([[2,0],[0,1]])
L

array([[2, 0],
       [0, 1]])

In [20]:
#lets take a transpose of the matrix c to apply vector L in all vecors of c and then multiply L with it
d = L @ (c.values).T

In [21]:
d.T

array([[ 2,  2],
       [-4,  3],
       [-4,  1],
       [ 6,  7],
       [ 8,  5],
       [12,  4]], dtype=int64)

Shifting of axes
Let's say from the original basis vectors i(1,0) and j(0,1) we want to shift it to the new orthonormal basis vectors i'(0.8,0.6) and j'(-0.6,0.8). What would be the location of the points in the newer basis?

In [70]:
L = np.array([[0.8,-0.6],[0.6,0.8]])
L

array([[ 0.8, -0.6],
       [ 0.6,  0.8]])

In [71]:
#Next you need to find its inverse and then use the transformation on the given set of points.
Ld = np.linalg.inv(L)
Ld

array([[ 0.8,  0.6],
       [-0.6,  0.8]])

In [24]:
d  = Ld @ (c.values).T
d.T

array([[ 2. ,  1. ],
       [ 0.2,  3.6],
       [-1. ,  2. ],
       [ 6.6,  3.8],
       [ 6.2,  1.6],
       [ 7.2, -0.4]])

In [25]:
#Linear transformation
a = [[1,2],[3,4],[5,6],[7,8]]
b = ['X','Y']
c = pd.DataFrame(a,columns=b)
c

X  Y
0  1  2
1  3  4
2  5  6
3  7  8

In [32]:
L = np.array([[1,4],[4,2]])
L

array([[1, 4],
       [4, 2]])

In [33]:
d = L @ (c.values).T
d

array([[ 9, 19, 29, 39],
       [ 8, 20, 32, 44]], dtype=int64)

In [34]:
d.T

array([[ 9,  8],
       [19, 20],
       [29, 32],
       [39, 44]], dtype=int64)

### Eigenvectors and Eigendecomposition

In [35]:
#Let's take the following matrix as an example
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [36]:
#Let's find the eigen vactor of A
k = np.linalg.eig(A)
k

(array([3., 1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [37]:
#Eigenvalues
k[0]

array([3., 1.])

In [38]:
#Eigenvactors
k[1]

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [43]:
#To verify this first calculate the Av
#Where A is the actual matrix and v is the eigen vector

A @ (k[1].T)[0]


array([2.12132034, 2.12132034])

In [45]:
#Now lets calculat the λv. Where λ is the eigen value which is 3 here and v is the eigenvactor
3 * (k[1].T)[0]

array([2.12132034, 2.12132034])

##### So here we can see Av = λv

#### Let's use the results we've obtained till now to do a neat little matrix manipulation that leads to a very important observation.

In [49]:
#First let's arrange the eigenvalues along the diagonal of a square matrix.
S = np.array([[3,0],[0,1]])
S

array([[3, 0],
       [0, 1]])

In [51]:
Q = k[1]
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [52]:
P = np.linalg.inv(Q)
P

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [53]:
# Now multiply Q,S & P
Q @ S @ P

array([[2., 1.],
       [1., 2.]])

##### This is called eigendecomposition of a matrix. 
Any matrix is multiplication of 3 other matrixes Q , S and P

Where : 
1. Q is the eigenvector matrix
2. S is a diagonal matrix with the eigenvalues as the diagonal elements
3. P is the inverse of the matrix Q.



In [54]:
#excercise question
v = np.array([[1,2,3],[2,3,1],[3,1,2]])
v

array([[1, 2, 3],
       [2, 3, 1],
       [3, 1, 2]])

In [56]:
Ev = np.linalg.eig(v)
Ev

(array([ 6.        , -1.73205081,  1.73205081]),
 array([[-0.57735027, -0.78867513,  0.21132487],
        [-0.57735027,  0.21132487, -0.78867513],
        [-0.57735027,  0.57735027,  0.57735027]]))

In [57]:
Ev[1]

array([[-0.57735027, -0.78867513,  0.21132487],
       [-0.57735027,  0.21132487, -0.78867513],
       [-0.57735027,  0.57735027,  0.57735027]])

In [61]:
#Excercise question
A = np.array([[3,0],[0,4]])
B = ['X','Y']
C = pd.DataFrame(A,columns=B)

In [74]:
L = np.array([[0,-1],[1,0]])
Li = np.linalg.inv(L)
Li

array([[ 0.,  1.],
       [-1., -0.]])

In [77]:
D = Li @ (C.values).T

In [78]:
D.T

array([[ 0., -3.],
       [ 4.,  0.]])

In [80]:
#excercise
A = np.array([[3/5,-4/5],[4/5,3/5]])
B = ['X','Y']
C = pd.DataFrame(A,columns=B)
C

X    Y
0  0.6 -0.8
1  0.8  0.6

In [84]:
P = np.array([[5,0],[0,0]])
P

array([[5, 0],
       [0, 0]])

In [85]:
D = P @ C
D

X    Y
0  3.0 -4.0
1  0.0  0.0

In [87]:
#Excercise - Variance

a = np.array([[1,2],[2,2],[3,4],[4,5],[4,6]])
C = ['X','Y']
D = pd.DataFrame(a, columns=C)
D


X  Y
0  1  2
1  2  2
2  3  4
3  4  5
4  4  6

In [89]:
np.var(D)

X    1.36
Y    2.56
dtype: float64

In [91]:
#doing basis transformation where new basis are (0.8,0.6), (-0.8,0.6)
P = np.array([[0.8,0.6],[-0.8,0.6]])
Pi = np.linalg.inv(P)
Pi

array([[ 0.625     , -0.625     ],
       [ 0.83333333,  0.83333333]])

In [110]:
#after basis transformation of matrix D

M = Pi @ D.T
M.T
data=pd.DataFrame((M.values).T,columns=C)
data
np.var(data)

X    0.156250
Y    5.166667
dtype: float64