In [1]:
import pandas as pd 
import numpy as np

In [2]:
#Let's take this dataset
a = [[0,0],[1,2],[2,3],[3,6],[4,8],[5,9]]
b = ['X','Y']
dat = pd.DataFrame(a,columns = b)
dat

X  Y
0  0  0
1  1  2
2  2  3
3  3  6
4  4  8
5  5  9

### Step 1 : Create the Covariance Matrix

In [4]:
C = np.cov(dat.T)
C

array([[ 3.5       ,  6.6       ],
       [ 6.6       , 12.66666667]])

### Step 2 : Eigendecomposition of the Covariance Matrix

In [5]:
eigenvalues, eigenvectors = np.linalg.eig(C)

In [6]:
eigenvalues

array([ 0.04797743, 16.11868923])

In [7]:
eigenvectors

array([[-0.88611393, -0.46346747],
       [ 0.46346747, -0.88611393]])

In [25]:
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvalues

array([16.11868923,  0.04797743])

In [26]:
eigenvectors = eigenvectors[:,idx]
eigenvectors

array([[-0.46346747, -0.88611393],
       [-0.88611393,  0.46346747]])

In [27]:
Cnew = np.linalg.inv(eigenvectors) @ dat.T

In [28]:
Cnew

0         1         2         3         4          5
0  0.0 -2.235695 -3.585277 -6.707086 -8.942781 -10.292363
1  0.0  0.040821 -0.381825  0.122463  0.163284  -0.259362

In [37]:
cols = np.array(['X','Y'])
CnewT = pd.DataFrame(Cnew.values,cols)
CnewT = CnewT.T
CnewT

X         Y
0   0.000000  0.000000
1  -2.235695  0.040821
2  -3.585277 -0.381825
3  -6.707086  0.122463
4  -8.942781  0.163284
5 -10.292363 -0.259362

In [38]:
100*np.var(CnewT)/sum(np.var(CnewT))

X    99.703232
Y     0.296768
dtype: float64

### Let's check it using pca function that we used earlier

In [39]:
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [40]:
pca.fit(dat)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [41]:
pca.components_

array([[-0.46346747, -0.88611393],
       [ 0.88611393, -0.46346747]])

In [42]:
pca.explained_variance_ratio_

array([0.99703232, 0.00296768])

#### Excercise question

In [43]:
data = pd.read_csv("Ratings.csv")

In [44]:
data

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2
5   4   2   4   3   4
6   4   3   1   5   5

In [45]:
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [46]:
pca.components_

array([[-0.31118649, -0.48101502,  0.35622281, -0.69199674, -0.25696953],
       [ 0.90672615, -0.31113879,  0.25507174, -0.09225738,  0.08641369],
       [-0.12857449, -0.38163517, -0.34923551, -0.16484744,  0.82986931],
       [ 0.1452065 , -0.34290409, -0.79235694, -0.05662208, -0.47989194],
       [-0.20831306, -0.63920934,  0.24134777,  0.69444104, -0.08671783]])

In [49]:
pca.explained_variance_ratio_.round(2)

array([0.65, 0.15, 0.13, 0.06, 0.  ])