In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
#Let's take this dataset
a = [[0,0],[1,2],[2,3],[3,6],[4,8],[5,9]]
b = ['X','Y']
dat = pd.DataFrame(a,columns = b)
dat

X  Y
0  0  0
1  1  2
2  2  3
3  3  6
4  4  8
5  5  9

In [5]:
#Covariance matrix
C = dat.T @ dat
C

X    Y
X   55  103
Y  103  194

In [8]:
eiganvalues,eigenvactors=np.linalg.eig(C)


In [9]:
eiganvalues

array([  0.24522142, 248.75477858])

In [10]:
eigenvactors

array([[-0.88298772, -0.46939609],
       [ 0.46939609, -0.88298772]])

In [13]:
idx = eiganvalues.argsort()[::-1]
eiganvalues = eiganvalues[idx]
eiganvalues

array([248.75477858,   0.24522142])

In [14]:
eigenvactors = eigenvactors[:,idx]
eigenvactors

array([[-0.46939609, -0.88298772],
       [-0.88298772,  0.46939609]])

#### Now let's use SVD

In [17]:
#Let'se use the SVD function from np.linalg library
U, s, Vt = np.linalg.svd(dat,full_matrices=False)

In [18]:
# U matrix shows each row in new theme(space)
U

array([[ 0.        ,  0.        ],
       [-0.14173072, -0.11269112],
       [-0.2274768 ,  0.72251284],
       [-0.42519217, -0.33807335],
       [-0.56692289, -0.45076447],
       [-0.65266896,  0.38443949]])

In [21]:
#s shows how strong the PCs are
# its a diagonal matrix
s

array([15.77196179,  0.49519836])

In [20]:
#Vt shows how the original variables(features or columns u can say) are mapped to new columns
# means its themes to column matrix
Vt

array([[-0.46939609, -0.88298772],
       [ 0.88298772, -0.46939609]])

### Relationship between the Matrices

Let's now take a look at how all these matrices are related. The key property that we would be verifying would be that U*s matrix is infact the same as the projection of the original dataset on the principal components

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [22]:
X = eigenvectors

NameError: name 'eigenvectors' is not defined